name: Lint

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: ShellCheck
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)"
          sudo apt-get install shellcheck

          for file in $(git ls-files '*.sh.tmpl'); do
              echo "Checking $file"
              ./bin/chezmoi execute-template < "$file" | shellcheck -
          done
