name: Lint

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io) -- init --apply no-yan --exclude=scripts"
      - name: ShellCheck
        run: |
          sudo apt-get install shellcheck

          for file in $(git ls-files '*.sh.tmpl'); do
              echo "Checking $file"
              ./bin/chezmoi execute-template < "$file" | shellcheck --exclude=SC1091 -
          done

          # Mock chezmoi's OS decetion to simulate MacOS environment
          echo 'chezmoi.os = "darwin"' > ~/.local/share/chezmoi/.chezmoidata.toml

          for file in $(git ls-files '*.sh.tmpl'); do
              echo "Checking $file"
              ./bin/chezmoi execute-template < "$file" | shellcheck --exclude=SC1091 -
          done
