name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  stylua:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        run: |
          shellcheck $(git ls-files '*.sh' '*.tmpl')
