name: "Install Test"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Install chezmoi and apply"
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply no-yan
      - run: brew list
