name: "Install Test"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install chezmoi and apply"
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply no-yan
      - run: brew list
