name: "Install Test"

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: "Install chezmoi and apply"
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin  init --apply no-yan
      - run: brew list
